"""Allow null chapter in highlights

Revision ID: 8d7d9c6f447a
Revises: f3fa8de8c800
Create Date: 2024-10-24 19:01:24.964666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d7d9c6f447a'
down_revision: Union[str, None] = 'f3fa8de8c800'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
